// <auto-generated />
namespace praktika.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FixTables1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixTables1));
        
        string IMigrationMetadata.Id
        {
            get { return "202211020646385_FixTables1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
